// <auto-generated />
namespace Redweb.BikeShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddImageUrlsToProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddImageUrlsToProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "201705301056469_AddImageUrlsToProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
